### ISSUE TITLE
Probably uploaded two folders containing .git folders

### ISSUE THREAD

**Issue by dhruvsh-1729** [deep-poharkar/DevOps#1]
Hey Deep! Dhruv here.
I'm not able to see the folder since I guess that folder might be containing another .git folder inside of it which has disabled click on it.
Hope you can resolve it and push the code again so that I can refer to it.
Regards
Dhruv

**Comment by deep-poharkar** [comment]
you're correct dhruv. actually i'm still working on the project but i will still push it without .git
